steps:
  # Step 1: Run unit tests
  - name: 'python:3.12-slim'
    entrypoint: bash
    args:
      - '-c'
      - |
        pip install -q -r requirements.txt -r requirements-dev.txt
        python -m pytest tests/ -q --tb=short

  # Step 2: Build the container image (Artifact Registry)
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/questforge/questforge:$COMMIT_SHA'
      - '-t'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/questforge/questforge:latest'
      - '.'

  # Step 3: Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/questforge/questforge'

  # Step 4: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'questforge-v2'
      - '--image=${_REGION}-docker.pkg.dev/$PROJECT_ID/questforge/questforge:$COMMIT_SHA'
      - '--region=${_REGION}'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--memory=512Mi'
      - '--cpu=1'
      - '--min-instances=0'
      - '--max-instances=10'
      - '--concurrency=80'
      - '--set-env-vars=ENABLE_FIRESTORE=true,ENABLE_TTS=true,ENABLE_TRANSLATE=true,ENABLE_STORAGE=true,ENABLE_IMAGEN=true,GOOGLE_API_KEY=${_GOOGLE_API_KEY},GCS_BUCKET_NAME=${_GCS_BUCKET_NAME}'

images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/questforge/questforge:$COMMIT_SHA'
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/questforge/questforge:latest'

substitutions:
  _GOOGLE_API_KEY: ''
  _GCS_BUCKET_NAME: ''
  _REGION: 'us-central1'

timeout: 1200s
